apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../local/

images:
  - name: ghcr.io/kaese72/authentication
    newName: ghcr.io/kaese72/authentication-development
    newTag: v0.0.4-20260920151349-efc1a8d
  - name: ghcr.io/kaese72/authentication-migrater
    newName: ghcr.io/kaese72/authentication-migrater-development
    newTag: v0.0.4-20260920151350-efc1a8d
  - name: ghcr.io/kaese72/device-store
    newName: ghcr.io/kaese72/device-store-development
    newTag: v0.0.64-20260920124149-631a32b
  - name: ghcr.io/kaese72/device-store-migrater
    newName: ghcr.io/kaese72/device-store-migrater-development
    newTag: v0.0.64-20260920124149-631a32b
  - name: ghcr.io/kaese72/huemie-ui
    newName: ghcr.io/kaese72/huemie-ui-development
    newTag: v0.0.6-20260920151836-b0e8d21
  - name: ghcr.io/kaese72/adapter-attendant
    newName: ghcr.io/kaese72/adapter-attendant-development
    newTag: v0.0.20-20260920124229-1978fc5
  - name: ghcr.io/kaese72/adapter-attendant-migrater
    newName: ghcr.io/kaese72/adapter-attendant-migrater-development
    newTag: v0.0.20-20260920124227-1978fc5
  - name: ghcr.io/kaese72/ittt-orchestrator
    newName: ghcr.io/kaese72/ittt-orchestrator-development
    newTag: v0.0.1-20260920124203-e98112b
  - name: ghcr.io/kaese72/ittt-orchestrator-migrater
    newName: ghcr.io/kaese72/ittt-orchestrator-migrater-development
    newTag: v0.0.1-20260920124200-e98112b
  - name: ghcr.io/kaese72/chatbot
    newName: ghcr.io/kaese72/chatbot-development
    newTag: v0.0.2-20260920124425-ca33762
  - name: ghcr.io/kaese72/chatbot-migrater
    newName: ghcr.io/kaese72/chatbot-migrater-development
    newTag: v0.0.2-20260920124426-ca33762
