apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../local/

images:
  - name: ghcr.io/kaese72/authentication
    newName: ghcr.io/kaese72/authentication-development
    newTag: v0.0.6-20260927103932-dcab5ce
  - name: ghcr.io/kaese72/authentication-migrater
    newName: ghcr.io/kaese72/authentication-migrater-development
    newTag: v0.0.6-20260927103933-dcab5ce
  - name: ghcr.io/kaese72/device-store
    newName: ghcr.io/kaese72/device-store-development
    newTag: v0.0.65-20260927164332-85cf62e
  - name: ghcr.io/kaese72/device-store-migrater
    newName: ghcr.io/kaese72/device-store-migrater-development
    newTag: v0.0.65-20260927164334-85cf62e
  - name: ghcr.io/kaese72/huemie-ui
    newName: ghcr.io/kaese72/huemie-ui-development
    newTag: v0.0.6-20260927164200-9c8f593
  - name: ghcr.io/kaese72/adapter-attendant
    newName: ghcr.io/kaese72/adapter-attendant-development
    newTag: v0.0.21-20260927104838-ba4abca
  - name: ghcr.io/kaese72/adapter-attendant-migrater
    newName: ghcr.io/kaese72/adapter-attendant-migrater-development
    newTag: v0.0.21-20260927104835-ba4abca
  - name: ghcr.io/kaese72/ittt-orchestrator
    newName: ghcr.io/kaese72/ittt-orchestrator-development
    newTag: v0.0.1-20260927104815-048d35a
  - name: ghcr.io/kaese72/ittt-orchestrator-migrater
    newName: ghcr.io/kaese72/ittt-orchestrator-migrater-development
    newTag: v0.0.1-20260927104815-048d35a
  - name: ghcr.io/kaese72/chatbot
    newName: ghcr.io/kaese72/chatbot-development
    newTag: v0.0.2-20260920124425-ca33762
  - name: ghcr.io/kaese72/chatbot-migrater
    newName: ghcr.io/kaese72/chatbot-migrater-development
    newTag: v0.0.2-20260920124426-ca33762
