apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../local/

images:
  - name: ghcr.io/kaese72/authentication
    newName: ghcr.io/kaese72/authentication-development
    newTag: v0.0.2-20260730212903-d658738
  - name: ghcr.io/kaese72/authentication-migrater
    newName: ghcr.io/kaese72/authentication-migrater-development
    newTag: v0.0.2-20260730212906-d658738
  - name: ghcr.io/kaese72/device-store
    newName: ghcr.io/kaese72/device-store-development
    newTag: v0.0.64-20260815174227-7b51f48
  - name: ghcr.io/kaese72/device-store-migrater
    newName: ghcr.io/kaese72/device-store-migrater-development
    newTag: v0.0.64-20260815174229-7b51f48
  - name: ghcr.io/kaese72/huemie-ui
    newName: ghcr.io/kaese72/huemie-ui-development
    newTag: v0.0.6-20260815112544-2babb72
  - name: ghcr.io/kaese72/adapter-attendant
    newName: ghcr.io/kaese72/adapter-attendant-development
    newTag: v0.0.20-20260517100140-a2bebb4
  - name: ghcr.io/kaese72/adapter-attendant-migrater
    newName: ghcr.io/kaese72/adapter-attendant-migrater-development
    newTag: v0.0.20-20260517100139-a2bebb4
  - name: ghcr.io/kaese72/ittt-orchestrator
    newName: ghcr.io/kaese72/ittt-orchestrator-development
    newTag: v0.0.1-20260730213019-eb691a3
  - name: ghcr.io/kaese72/ittt-orchestrator-migrater
    newName: ghcr.io/kaese72/ittt-orchestrator-migrater-development
    newTag: v0.0.1-20260730213012-eb691a3
  - name: ghcr.io/kaese72/chatbot
    newName: ghcr.io/kaese72/chatbot-development
    newTag: v0.0.2-20260814203954-16c7bad
  - name: ghcr.io/kaese72/chatbot-migrater
    newName: ghcr.io/kaese72/chatbot-migrater-development
    newTag: v0.0.2-20260814203951-16c7bad
