apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adapters

resources:
 - namespace.yaml
 - ../../base/adapters

patches:
  - target:
      kind: RoleBinding
      name: adapter-attendant-adapter-admin-binding
    patch: |-
      - op: add
        path: /subjects/0/namespace
        value: huemie-local