---
apiVersion: v1
data:
  password: bWFyaWFkYnNlY3JldHBhc3N3b3Jk
kind: Secret
metadata:
  name: mariadb-root-password
type: Opaque
---
apiVersion: v1
data:
  my.cnf: "[mysqld]\r\nbind-address = 0.0.0.0"
kind: ConfigMap
metadata:
  name: mariadb-config
---
apiVersion: v1
data:
  init.sql: "CREATE DATABASE IF NOT EXISTS devicestore; CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'databaseuserpassword'; GRANT ALL PRIVILEGES ON devicestore.* TO 'user'@'%' IDENTIFIED BY 'databaseuserpassword';"
kind: ConfigMap
metadata:
  name: mariadb-init-sql

---
apiVersion: v1
metadata:
  name: mariadb-user-creds
data:
  password: ZGF0YWJhc2V1c2VycGFzc3dvcmQ=
  username: dXNlcg==
kind: Secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d/
        - name: mariadb-pv
          mountPath: /var/lib/mysql
        - name: mariadb-init-sql
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: password
        resources:
          limits:
            cpu: 1000m
            memory: 512M
          requests:
            cpu: 500m
            memory: 512M
      volumes:
      - name: config-volume
        configMap:
          name: mariadb-config
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: mariadb-init-sql
        configMap:
          name: mariadb-init-sql
          items:
            - key: init.sql
              path: init.sql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
status:
  loadBalancer: {}
