---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  definitions.json: |-
    # RabbitMQ definitions go here
  enabled_plugins: '[rabbitmq_peer_discovery_k8s].'
  rabbitmq.conf: |-
    # RabbitMQ configuration options go here
    # Only for local development:
    loopback_users = none
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        huemie.space/service-role: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4-management
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: http
              containerPort: 15672
              protocol: TCP
          livenessProbe:
              exec:
                command:
                - rabbitmq-diagnostics
                - status
              initialDelaySeconds: 60
              periodSeconds: 60
              timeoutSeconds: 15
          readinessProbe:
              exec:
                command:
                - rabbitmq-diagnostics
                - ping
              initialDelaySeconds: 20
              periodSeconds: 60
              timeoutSeconds: 10
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 200m
              memory: 256M
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-configmap 
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  # Add labels and annotations as per your requirements
spec:
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq
spec:
  podSelector:
    matchLabels:
      huemie.space/service-role: rabbitmq
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              huemie.space/service-role: device-store
      ports:
        - port: 5672
    - from:
        - podSelector:
            matchLabels:
              huemie.space/service-role: ittt-orchestrator
      ports:
        - port: 5672
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
