---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huemie-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  rules:
    - host: app.huemie.space
      http:
        paths:
          - path: /device-store
            pathType: Prefix
            backend:
              service:
                name: device-store
                port:
                  number: 8080
          - path: /device-ingest
            pathType: Prefix
            backend:
              service:
                name: device-store
                port:
                  number: 8080
          - path: /adapter-attendant
            pathType: Prefix
            backend:
              service:
                name: adapter-attendant
                port:
                  number: 8080
          - path: /huemie-ui
            pathType: Prefix
            backend:
              service:
                name: huemie-ui
                port:
                  number: 80
