apiVersion: apps/v1
kind: Deployment
metadata:
  name: huemie-ui
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: huemie-ui
  template:
    metadata:
      labels:
        app: huemie-ui
        huemie-owner: core
    spec:
      containers:
        - name: huemie-ui
          image: ghcr.io/kaese72/huemie-ui:v0.0.3
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 256M
            requests:
              cpu: 500m
              memory: 256M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: huemie-ui
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  name: huemie-ui
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: huemie-ui
status:
  loadBalancer: {}
