apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../local/

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: huemie-ingress
    path: patch-ingress-add-local-host.yaml

images:
  - name: ghcr.io/kaese72/authentication
    newName: ghcr.io/kaese72/authentication-development
    newTag: v0.0.2-20260516231525-bc081e1
  - name: ghcr.io/kaese72/authentication-migrater
    newName: ghcr.io/kaese72/authentication-migrater-development
    newTag: v0.0.2-20260516231529-bc081e1
  - name: ghcr.io/kaese72/device-store
    newName: ghcr.io/kaese72/device-store-development
    newTag: v0.0.64-20260517090236-07a978a
  - name: ghcr.io/kaese72/device-store-migrater
    newName: ghcr.io/kaese72/device-store-migrater-development
    newTag: v0.0.64-20260517090237-07a978a
  - name: ghcr.io/kaese72/huemie-ui
    newName: ghcr.io/kaese72/huemie-ui-development
    newTag: v0.0.6-20260516233556-e8853d6
  - name: ghcr.io/kaese72/adapter-attendant
    newName: ghcr.io/kaese72/adapter-attendant-development
    newTag: v0.0.20-20260517085827-44886ee
  - name: ghcr.io/kaese72/adapter-attendant-migrater
    newName: ghcr.io/kaese72/adapter-attendant-migrater-development
    newTag: v0.0.20-20260517085827-44886ee
  - name: ghcr.io/kaese72/ittt-orchestrator
    newName: ghcr.io/kaese72/ittt-orchestrator-development
    newTag: v0.0.1-20260517085530-50f7d3c
  - name: ghcr.io/kaese72/ittt-orchestrator-migrater
    newName: ghcr.io/kaese72/ittt-orchestrator-migrater-development
    newTag: v0.0.1-20260517085530-50f7d3c