apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../local/

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: huemie-ingress
    path: patch-ingress-add-local-host.yaml

images:
  - name: ghcr.io/kaese72/device-store
    newName: ghcr.io/kaese72/device-store-development
    newTag: v0.0.63-20260221125333-f8e751c
  - name: ghcr.io/kaese72/device-store-migrater
    newName: ghcr.io/kaese72/device-store-migrater-development
    newTag: v0.0.63-20260221125336-f8e751c
  - name: ghcr.io/kaese72/huemie-ui
    newName: ghcr.io/kaese72/huemie-ui-development
    newTag: v0.0.5-20260222221836-e1e3b23
  - name: ghcr.io/kaese72/adapter-attendant
    newName: ghcr.io/kaese72/adapter-attendant-development
    newTag: v0.0.19-20260208124436-27c9924
  - name: ghcr.io/kaese72/adapter-attendant-migrater
    newName: ghcr.io/kaese72/adapter-attendant-migrater-development
    newTag: v0.0.19-20260208124431-27c9924